name: aida_workshop_gnn
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python=3.9
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - jupyter
  - ipython
  - lightning
  - pyg # Pytorch Geometric
# The following are good packages to have with Pytorch Geometric, but causes issues with dynamic libraries
#  - pytorch-cluster
#  - pytorch-scatter
#  - pytorch-sparse
#  - pytorch-spline-conv

